id: a0487b0f0d454dce9b577c17292c6582
initial_creation_type: ocr
source_metadata:
  volumes:
    2b0c733208a24700b8c8306a8ac0a559:
      base_file: v110.txt
      image_group_id: I1PD95956
      title: སློབ་དཔོན་ཀླུ་སྒྲུབ་ཀྱིས་བཤད་པ་སྨན་ཨ་བའི་ཆོ་ག།
      total_pages: 1182
      volume_number: 111
